COUNTRY_EN = {
    "Afganistán": "Afghanistan",
    "Albania": "Albania",
    "Alemania": "Germany",
    "Andorra": "Andorra",
    "Angola": "Angola",
    "Anguila": "Anguilla",
    "Antártida": "Antarctica",
    "Antigua Y Barbuda": "Antigua and Barbuda",
    "Arabia Saudita": "Saudi Arabia",
    "Argelia": "Algeria",
    "Argentina": "Argentina",
    "Armenia": "Armenia",
    "Aruba": "Aruba",
    "Australia": "Australia",
    "Austria": "Austria",
    "Azerbaiyán": "Azerbaijan",
    "Bahamas": "Bahamas",
    "Bahrein": "Bahrain",
    "Bangladesh": "Bangladesh",
    "Barbados": "Barbados",
    "Belarús": "Belarus",
    "Bélgica": "Belgium",
    "Belice": "Belize",
    "Benin": "Benin",
    "Bermuda": "Bermuda",
    "Bolivia (Estado Plurinacional De)": "Bolivia",
    "Bonaire, San Eustaquio Y Saba": "Bonaire, Saint Eustatius and Saba",
    "Bosnia Y Herzegovina": "Bosnia and Herzegovina",
    "Botswana": "Botswana",
    "Brasil": "Brazil",
    "Brunei Darussalam": "Brunei",
    "Bulgaria": "Bulgaria",
    "Burkina Faso": "Burkina Faso",
    "Burundi": "Burundi",
    "Bután": "Bhutan",
    "Cabo Verde": "Cape Verde",
    "Camboya": "Cambodia",
    "Camerún": "Cameroon",
    "Canadá": "Canada",
    "Chad": "Chad",
    "Chile": "Chile",
    "China": "China",
    "Chipre": "Cyprus",
    "Colombia": "Colombia",
    "Comoras": "Comoros",
    "Congo": "Republic of the Congo",
    "Costa De Marfil": "Ivory Coast",
    "Costa Rica": "Costa Rica",
    "Croacia": "Croatia",
    "Cuba": "Cuba",
    "Curazao": "Curacao",
    "Dinamarca": "Denmark",
    "Djibouti": "Djibouti",
    "Dominica": "Dominica",
    "Ecuador": "Ecuador",
    "Egipto": "Egypt",
    "El Salvador": "El Salvador",
    "Emiratos Árabes Unidos": "United Arab Emirates",
    "Eritrea": "Eritrea",
    "Eslovaquia": "Slovakia",
    "Eslovenia": "Slovenia",
    "España": "Spain",
    "Estado De Palestina": "Palestine",
    "Estados Unidos De América": "United States",
    "Estonia": "Estonia",
    "Eswatini": "Eswatini",
    "Etiopía": "Ethiopia",
    "Federación De Rusia": "Russia",
    "Fiji": "Fiji",
    "Filipinas": "Philippines",
    "Finlandia": "Finland",
    "Francia": "France",
    "Gabón": "Gabon",
    "Gambia": "Gambia",
    "Georgia": "Georgia",
    "Ghana": "Ghana",
    "Gibraltar": "Gibraltar",
    "Granada": "Grenada",
    "Grecia": "Greece",
    "Groenlandia": "Greenland",
    "Guadalupe": "Guadeloupe",
    "Guam": "Guam",
    "Guatemala": "Guatemala",
    "Guayana Francesa": "French Guiana",
    "Guernsey": "Guernsey",
    "Guinea": "Guinea",
    "Guinea-Bissau": "Guinea-Bissau",
    "Guinea Ecuatorial": "Equatorial Guinea",
    "Guyana": "Guyana",
    "Haití": "Haiti",
    "Honduras": "Honduras",
    "Hong Kong": "Hong Kong",
    "Hungría": "Hungary",
    "India": "India",
    "Indonesia": "Indonesia",
    "Irán (República Islámica Del)": "Iran",
    "Iraq": "Iraq",
    "Irlanda": "Ireland",
    "Isla Bouvet": "Bouvet Island",
    "Isla Christmas": "Christmas Island",
    "Isla De Man": "Isle of Man",
    "Isla Johnston": "United States Minor Outlying Islands",
    "Isla Norfolk": "Norfolk Island",
    "Isla Wake": "United States Minor Outlying Islands",
    "Islandia": "Iceland",
    "Islas Åland": "Aland Islands",
    "Islas Caimán": "Cayman Islands",
    "Islas Cocos (Keeling)": "Cocos Islands",
    "Islas Cook": "Cook Islands",
    "Islas Del Canal": "Channel Islands",
    "Islas Feroe": "Faroe Islands",
    "Islas Heard Y Mcdonald": "Heard Island and McDonald Islands",
    "Islas Malvinas (Falkland)": "Falkland Islands",
    "Islas Marianas Septentrionales": "Northern Mariana Islands",
    "Islas Marshall": "Marshall Islands",
    "Islas Menores Alejadas De Estados Unidos": "United States Minor Outlying Islands",
    "Islas Salomón": "Solomon Islands",
    "Islas Svalbard Y Jan Mayen": "Svalbard and Jan Mayen",
    "Islas Turcas Y Caicos": "Turks and Caicos Islands",
    "Islas Vírgenes Británicas": "British Virgin Islands",
    "Islas Vírgenes De Los Estados Unidos": "United States Virgin Islands",
    "Islas Wallis Y Futuna": "Wallis and Futuna",
    "Israel": "Israel",
    "Italia": "Italy",
    "Jamaica": "Jamaica",
    "Japón": "Japan",
    "Jersey": "Jersey",
    "Jordania": "Jordan",
    "Kazajstán": "Kazakhstan",
    "Kenya": "Kenya",
    "Kirguistán": "Kyrgyzstan",
    "Kiribati": "Kiribati",
    "Kosovo": "Kosovo",
    "Kuwait": "Kuwait",
    "Lesotho": "Lesotho",
    "Letonia": "Latvia",
    "Líbano": "Lebanon",
    "Liberia": "Liberia",
    "Libia": "Libya",
    "Liechtenstein": "Liechtenstein",
    "Lituania": "Lithuania",
    "Luxemburgo": "Luxembourg",
    "Macao": "Macao",
    "Macedonia Del Norte": "North Macedonia",
    "Madagascar": "Madagascar",
    "Malasia": "Malaysia",
    "Malawi": "Malawi",
    "Maldivas": "Maldives",
    "Malí": "Mali",
    "Malta": "Malta",
    "Marruecos": "Morocco",
    "Martinica": "Martinique",
    "Mauricio": "Mauritius",
    "Mauritania": "Mauritania",
    "Mayotte": "Mayotte",
    "México": "Mexico",
    "Micronesia (Estados Federados De)": "Micronesia",
    "Mónaco": "Monaco",
    "Mongolia": "Mongolia",
    "Montenegro": "Montenegro",
    "Montserrat": "Montserrat",
    "Mozambique": "Mozambique",
    "Myanmar": "Myanmar",
    "Namibia": "Namibia",
    "Nauru": "Nauru",
    "Nepal": "Nepal",
    "Nicaragua": "Nicaragua",
    "Níger": "Niger",
    "Nigeria": "Nigeria",
    "Niue": "Niue",
    "Noruega": "Norway",
    "Nueva Caledonia": "New Caledonia",
    "Nueva Zelanda": "New Zealand",
    "Omán": "Oman",
    "Países Bajos": "Netherlands",
    "Pakistán": "Pakistan",
    "Palau": "Palau",
    "Panamá": "Panama",
    "Papúa Nueva Guinea": "Papua New Guinea",
    "Paraguay": "Paraguay",
    "Perú": "Peru",
    "Pitcairn": "Pitcairn Islands",
    "Polinesia Francesa": "French Polynesia",
    "Polonia": "Poland",
    "Portugal": "Portugal",
    "Puerto Rico": "Puerto Rico",
    "Qatar": "Qatar",
    "Reino Unido De Gran Bretaña E Irlanda Del Norte": "United Kingdom",
    "República Árabe Siria": "Syria",
    "República Centroafricana": "Central African Republic",
    "Republica Checa": "Czech Republic",
    "República De Corea": "South Korea",
    "República Democrática Del Congo": "Democratic Republic of the Congo",
    "República Democrática Popular Lao": "Laos",
    "República De Moldova": "Moldova",
    "República Dominicana": "Dominican Republic",
    "República Popular Democrática De Corea": "North Korea",
    "República Unida De Tanzanía": "Tanzania",
    "Reunión": "Reunion",
    "Ruanda": "Rwanda",
    "Rumania": "Romania",
    "Sahara Occidental": "Western Sahara",
    "Saint Kitts Y Nevis": "Saint Kitts and Nevis",
    "Samoa": "Samoa",
    "Samoa Americana": "American Samoa",
    "San Marino": "San Marino",
    "San Martín (Parte Francesa)": "Saint Martin",
    "San Martín (Parte Holandesa)": "Sint Maarten",
    "San Pedro Y Miquelón": "Saint Pierre and Miquelon",
    "Santa Elena": "Saint Helena",
    "Santa Lucía": "Saint Lucia",
    "Santa Sede": "Vatican City",
    "Santo Tomé Y Príncipe": "Sao Tome and Principe",
    "San Vicente Y Las Granadinas": "Saint Vincent and the Grenadines",
    "Senegal": "Senegal",
    "Serbia": "Serbia",
    "Seychelles": "Seychelles",
    "Sierra Leona": "Sierra Leone",
    "Singapur": "Singapore",
    "Somalia": "Somalia",
    "Sri Lanka": "Sri Lanka",
    "Sudáfrica": "South Africa",
    "Sudán": "Sudan",
    "Sudán Del Sur": "South Sudan",
    "Suecia": "Sweden",
    "Suiza": "Switzerland",
    "Surinam": "Suriname",
    "Tailandia": "Thailand",
    "Taiwán (Provincia De China)": "Taiwan",
    "Tayikistán": "Tajikistan",
    "Territorio Británico Del Océano Índico": "British Indian Ocean Territory",
    "Territorio De Las Tierras Australes Francesas": "French Southern Territories",
    "Timor-Leste": "Timor-Leste",
    "Togo": "Togo",
    "Tokelau": "Tokelau",
    "Tonga": "Tonga",
    "Trinidad Y Tobago": "Trinidad and Tobago",
    "Túnez": "Tunisia",
    "Turkmenistán": "Turkmenistan",
    "Turquía": "Turkey",
    "Tuvalu": "Tuvalu",
    "Ucrania": "Ukraine",
    "Uganda": "Uganda",
    "Uruguay": "Uruguay",
    "Uzbekistán": "Uzbekistan",
    "Vanuatu": "Vanuatu",
    "Venezuela (República Bolivariana De)": "Venezuela",
    "Viet Nam": "Vietnam",
    "Yemen": "Yemen",
    "Zambia": "Zambia",
    "Zimbabwe": "Zimbabwe",
}

COL_MAP = {
    ("Inbound",  "Total"):  "Total_in",
    ("Inbound",  "Female"): "Femenino_in",
    ("Inbound",  "Male"):   "Masculino_in",
    ("Outbound", "Total"):  "Total_out",
    ("Outbound", "Female"): "Femenino_out",
    ("Outbound", "Male"):   "Masculino_out",
}

METRIC_LABEL = {"Total": "People", "Female": "Women", "Male": "Men"}

VIEW = ["General", "Migration"]
