from generalities.function import BASE_DIR

DEATHS_PATHS = {
    "total":         BASE_DIR / "data/dane/deaths/total.csv",
    "area_age":      BASE_DIR / "data/dane/deaths/area_grupo_edad.csv",
    "dept_death":    BASE_DIR / "data/dane/deaths/departamento_muerte.csv",
    "dept_residence": BASE_DIR / "data/dane/deaths/departamento_residencia.csv",
}

DEATHS_COMPARE = ["Gender", "Age Group", "Area", "Department", "Cause (Top 5)", "Cause (Compare)"]

GENDER_EN = {"Hombres": "Men", "Mujeres": "Women", "Indeterminado": "Undetermined"}

AREA_EN = {
    "Cabecera municipal": "Municipal seat",
    "Centro poblado":     "Populated center",
    "Rural disperso":     "Dispersed rural",
    "Sin información":     "Unknown",
}

# Both spellings of the cleaning typos map to one label so `grupo_edad.map(AGE_EN)` works.
AGE_EN = {
    "Menor de 1 hora":   "Under 1 hour",
    "Menor 1 hora":      "Under 1 hour",
    "De 1 a 23 horas":   "1–23 hours",
    "De 1 a 6 días":     "1–6 days",
    "De 7 a 27 días":    "7–27 days",
    "De 7 a 27 dias":    "7–27 days",
    "De 28 a 29 días":   "28–29 days",
    "De 1 a 5 meses":    "1–5 months",
    "De 6 a 11 meses":   "6–11 months",
    "De 1 año":          "1 year",
    "De 2 a 4 años":     "2–4",
    "De 5 a 9 años":     "5–9",
    "De 10 a 14 años":   "10–14",
    "De 15 a 19 años":   "15–19",
    "De 20 a 24 años":   "20–24",
    "De 25 a 29 años":   "25–29",
    "De 30 a 34 años":   "30–34",
    "De 35 a 39 años":   "35–39",
    "De 40 a 44 años":   "40–44",
    "De 45 a 49 años":   "45–49",
    "De 50 a 54 años":   "50–54",
    "De 55 a 59 años":   "55–59",
    "De 60 a 64 años":   "60–64",
    "De 65 a 69 años":   "65–69",
    "De 70 a 74 años":   "70–74",
    "De 75 a 79 años":   "75–79",
    "De 80 a 84 años":   "80–84",
    "De 85 a 89 años":   "85–89",
    "De 90 a 94 años":   "90–94",
    "De 95 a 99 años":   "95–99",
    "De 100 años y más": "100+",
    "Edad desconocida":  "Unknown",
}

# Keyed on norm(stripped Spanish cause); accent variants collapse to one entry.
CAUSE_EN = {
    "accidentes de transporte de motor y secuelas": "Motor transport accidents and sequelae",
    "accidentes por disparo de arma de fuego": "Firearm discharge accidents",
    "agresiones (homicidios) y secuelas": "Assault (homicide) and sequelae",
    "ahogamiento y sumersion accidentales": "Accidental drowning and submersion",
    "anemias: nutricionales, hemoliticas, aplasticas y otras": "Anemias: nutritional, hemolytic, aplastic and others",
    "aneurisma aortico": "Aortic aneurysm",
    "aterosclerosis": "Atherosclerosis",
    "caidas": "Falls",
    "ciertas enfermedades inmunoprevenibles": "Certain vaccine-preventable diseases",
    "ciertas enfermedades transmitidas por vectores y rabia": "Certain vector-borne diseases and rabies",
    "contratiempos de la atencion medico quirurgica y secuelas": "Misadventures of surgical and medical care and sequelae",
    "defectos de coagulacion, purpura y otras afecciones hemorragicas y de la sangre y los trastornos que afectan la inmunidad": "Coagulation defects, purpura and other hemorrhagic and blood conditions and immunity disorders",
    "deficiencias nutricionales": "Nutritional deficiencies",
    "diabetes mellitus": "Diabetes mellitus",
    "embarazo, parto y puerperio": "Pregnancy, childbirth and puerperium",
    "enfermedad cardiopulmonar y enfermedades de la circulacion pulmonar": "Cardiopulmonary disease and pulmonary circulation diseases",
    "enfermedad por el vih (sida)": "HIV disease (AIDS)",
    "enfermedades cerebrovasculares": "Cerebrovascular diseases",
    "enfermedades cronicas de las vias respiratorias inferiores": "Chronic lower respiratory diseases",
    "enfermedades de la piel y del tejido subcutaneo": "Diseases of the skin and subcutaneous tissue",
    "enfermedades de los vasos sanguineos y otras enfermedades del sistema circulatorio": "Diseases of blood vessels and other circulatory system diseases",
    "enfermedades del apendice, hernia y obstruccion intestinal": "Diseases of the appendix, hernia and intestinal obstruction",
    "enfermedades del esofago y otras enfermedades del estomago y del duodeno": "Diseases of the esophagus and other diseases of the stomach and duodenum",
    "enfermedades del higado": "Liver diseases",
    "enfermedades del ojo y sus anexos, del oido y de la apofisis mastoides": "Diseases of the eye and adnexa, ear and mastoid process",
    "enfermedades del peritoneo y todas las demas enfermedades del sistema digestivo": "Diseases of the peritoneum and all other digestive system diseases",
    "enfermedades del pulmon debidas a agentes externos": "Lung diseases due to external agents",
    "enfermedades del sistema osteomuscular y del tejido conjuntivo": "Diseases of the musculoskeletal system and connective tissue",
    "enfermedades glomerulares y tubulointersticiales": "Glomerular and tubulointerstitial diseases",
    "enfermedades hipertensivas": "Hypertensive diseases",
    "enfermedades infecciosas intestinales": "Intestinal infectious diseases",
    "enfermedades isquemicas del corazon": "Ischemic heart diseases",
    "enteritis, colitis no infecciosa y otras enfermedades de los intestinos": "Enteritis, non-infectious colitis and other intestinal diseases",
    "enterocolitis necrotizante del feto y del recien nacido": "Necrotizing enterocolitis of fetus and newborn",
    "envenenamiento accidental por, y exposicion a sustancias nocivas": "Accidental poisoning by and exposure to noxious substances",
    "epilepsia y otros trastornos episodicos y paroxisticos": "Epilepsy and other episodic and paroxysmal disorders",
    "eventos de intencion no determinada y secuelas": "Events of undetermined intent and sequelae",
    "exposicion a la corriente electrica, radiacion y temperatura y presion del aire ambientales extremas": "Exposure to electric current, radiation and extreme ambient air temperature and pressure",
    "exposicion al humo, fuego y llamas": "Exposure to smoke, fire and flames",
    "feto y recien nacido afectados por ciertas afecciones maternas": "Fetus and newborn affected by certain maternal conditions",
    "feto y recien nacido afectados por complicaciones obstetricas y traumatismo del nacimiento": "Fetus and newborn affected by obstetric complications and birth trauma",
    "fiebre reumatica aguda y enfermedades cardiacas reumaticas cronicas": "Acute rheumatic fever and chronic rheumatic heart diseases",
    "hemorragia gastrointestinal": "Gastrointestinal hemorrhage",
    "hepatitis viral y secuelas": "Viral hepatitis and sequelae",
    "hiperplasia de la prostata": "Hyperplasia of the prostate",
    "infecciones especificas del periodo perinatal": "Infections specific to the perinatal period",
    "insuficiencia cardiaca": "Heart failure",
    "insuficiencia renal": "Renal failure",
    "intervencion legal y operaciones de guerra y secuelas": "Legal intervention and operations of war and sequelae",
    "las demas malformaciones congenitas, deformidades y anomalias congenitas": "Other congenital malformations, deformities and congenital anomalies",
    "lesiones autoinfligidas intencionalmente (suicidios) y secuelas": "Intentional self-harm (suicide) and sequelae",
    "leucemia": "Leukemia",
    "los demas accidentes de transporte y los no especificados y secuelas": "Other and unspecified transport accidents and sequelae",
    "malformaciones congenitas del sistema circulatorio": "Congenital malformations of the circulatory system",
    "melanoma y otros tumores malignos de la piel": "Melanoma and other malignant skin tumors",
    "meningitis y otras enfermedades inflamatorias del sistema nervioso central": "Meningitis and other inflammatory diseases of the central nervous system",
    "neumonia": "Pneumonia",
    "otros accidentes de transporte terrestre": "Other land transport accidents",
    "otros accidentes que obstruyen la respiracion": "Other accidents obstructing breathing",
    "otros accidentes y secuelas": "Other accidents and sequelae",
    "retardo del crecimiento fetal, desnutricion fetal, gestacion corta y bajo peso al nacer": "Slow fetal growth, fetal malnutrition, short gestation and low birth weight",
    "septicemia, excepto neonatal": "Septicemia, except neonatal",
    "signos, sintomas y afecciones mal definidas": "Signs, symptoms and ill-defined conditions",
    "sifilis y otras enfermedades venereas": "Syphilis and other venereal diseases",
    "todas las demas afecciones originadas en el periodo perinatal": "All other conditions originating in the perinatal period",
    "todas las demas enfermedades bacterianas": "All other bacterial diseases",
    "todas las demas enfermedades del sistema nervioso": "All other nervous system diseases",
    "todas las demas enfermedades del sistema respiratorio": "All other respiratory system diseases",
    "todas las demas enfermedades del sistema urinario": "All other urinary system diseases",
    "todas las demas enfermedades endocrinas y nutricionales": "All other endocrine and nutritional diseases",
    "todas las demas enfermedades infecciosas y parasitarias": "All other infectious and parasitic diseases",
    "todas las demas formas de enfermedad del corazon": "All other forms of heart disease",
    "todos los demas tumores malignos de los organos digestivos y del peritoneo": "All other malignant tumors of the digestive organs and peritoneum",
    "todos los demas tumores malignos de los organos respiratorios e intratoracicos, excepto traquea, bronquios y pulmon": "All other malignant tumors of the respiratory and intrathoracic organs, except trachea, bronchi and lung",
    "todos los demas tumores malignos de los organos urinarios": "All other malignant tumors of the urinary organs",
    "todos los demas tumores malignos de otras localizaciones": "All other malignant tumors of other sites",
    "todos los demas tumores malignos del tejido linfatico, de los organos hematopoyeticos y de tejidos afines": "All other malignant tumors of lymphatic tissue, hematopoietic organs and related tissues",
    "trastornos de la vesicula biliar, de las vias biliares y del pancreas": "Disorders of the gallbladder, biliary tract and pancreas",
    "trastornos de los organos genitales": "Disorders of the genital organs",
    "trastornos hemorragicos y hematologicos del feto y del recien nacido": "Hemorrhagic and hematological disorders of the fetus and newborn",
    "trastornos mentales y del comportamiento": "Mental and behavioral disorders",
    "trastornos respiratorios especificos del periodo perinatal": "Respiratory disorders specific to the perinatal period",
    "tuberculosis y secuelas": "Tuberculosis and sequelae",
    "tumor maligno de la laringe": "Malignant tumor of the larynx",
    "tumor maligno de la mama de la mujer": "Malignant tumor of the female breast",
    "tumor maligno de la prostata": "Malignant tumor of the prostate",
    "tumor maligno de la traquea, los bronquios y el pulmon": "Malignant tumor of the trachea, bronchi and lung",
    "tumor maligno de la vejiga urinaria": "Malignant tumor of the urinary bladder",
    "tumor maligno de la vesicula biliar y de las vias biliares": "Malignant tumor of the gallbladder and biliary tract",
    "tumor maligno de los huesos y de los cartilagos articulares": "Malignant tumor of bones and articular cartilage",
    "tumor maligno de otras partes del utero": "Malignant tumor of other parts of the uterus",
    "tumor maligno de sitios no especificados": "Malignant tumor of unspecified sites",
    "tumor maligno del colon, de la union rectosigmoidea, recto y ano": "Malignant tumor of the colon, rectosigmoid junction, rectum and anus",
    "tumor maligno del cuello del utero": "Malignant tumor of the cervix",
    "tumor maligno del encefalo, del ojo y de otras partes del sistema nervioso central": "Malignant tumor of the brain, eye and other parts of the central nervous system",
    "tumor maligno del estomago": "Malignant tumor of the stomach",
    "tumor maligno del esofago": "Malignant tumor of the esophagus",
    "tumor maligno del higado": "Malignant tumor of the liver",
    "tumor maligno del ovario": "Malignant tumor of the ovary",
    "tumor maligno del pancreas": "Malignant tumor of the pancreas",
    "tumor maligno del tiroides y de otras glandulas endocrinas": "Malignant tumor of the thyroid and other endocrine glands",
    "tumores malignos de sitios mal definidos y secundarios": "Malignant tumors of ill-defined and secondary sites",
    "tumores malignos del labio, de la cavidad bucal y de la faringe": "Malignant tumors of the lip, oral cavity and pharynx",
    "tumores: in situ, benignos y de comportamiento incierto o desconocido y los no especificados": "Tumors: in situ, benign and of uncertain or unknown behavior and unspecified",
    "ulcera": "Ulcer",
}
