from generalities.function import BASE_DIR

DEATHS_PATHS = {
    "total":         BASE_DIR / "data/dane/deaths/total.csv",
    "area_age":      BASE_DIR / "data/dane/deaths/area_grupo_edad.csv",
    "dept_death":    BASE_DIR / "data/dane/deaths/departamento_muerte.csv",
    "dept_residence": BASE_DIR / "data/dane/deaths/departamento_residencia.csv",
    "muni_residence": BASE_DIR / "data/dane/deaths/departamento_municipio_residencia.csv",
}

DEATHS_COMPARE = ["Gender", "Age Group", "Area", "Department", "Municipality", "Cause (Top 5)", "Cause (Compare)"]

GENDER_EN = {"Hombres": "Men", "Mujeres": "Women", "Indeterminado": "Undetermined"}

AREA_EN = {
    "Cabecera municipal": "Municipal seat",
    "Centro poblado":     "Populated center",
    "Rural disperso":     "Dispersed rural",
    "Sin información":     "Unknown",
}

# Both spellings of the cleaning typos map to one label so `grupo_edad.map(AGE_EN)` works.
AGE_EN = {
    "Menor de 1 hora":   "Under 1 hour",
    "Menor 1 hora":      "Under 1 hour",
    "De 1 a 23 horas":   "1–23 hours",
    "De 1 a 6 días":     "1–6 days",
    "De 7 a 27 días":    "7–27 days",
    "De 7 a 27 dias":    "7–27 days",
    "De 28 a 29 días":   "28–29 days",
    "De 1 a 5 meses":    "1–5 months",
    "De 6 a 11 meses":   "6–11 months",
    "De 1 año":          "1 year",
    "De 2 a 4 años":     "2–4",
    "De 5 a 9 años":     "5–9",
    "De 10 a 14 años":   "10–14",
    "De 15 a 19 años":   "15–19",
    "De 20 a 24 años":   "20–24",
    "De 25 a 29 años":   "25–29",
    "De 30 a 34 años":   "30–34",
    "De 35 a 39 años":   "35–39",
    "De 40 a 44 años":   "40–44",
    "De 45 a 49 años":   "45–49",
    "De 50 a 54 años":   "50–54",
    "De 55 a 59 años":   "55–59",
    "De 60 a 64 años":   "60–64",
    "De 65 a 69 años":   "65–69",
    "De 70 a 74 años":   "70–74",
    "De 75 a 79 años":   "75–79",
    "De 80 a 84 años":   "80–84",
    "De 85 a 89 años":   "85–89",
    "De 90 a 94 años":   "90–94",
    "De 95 a 99 años":   "95–99",
    "De 100 años y más": "100+",
    "Edad desconocida":  "Unknown",
}

# Keyed on norm(stripped Spanish cause); accent variants collapse to one entry.
CAUSE_EN = {
    "accidentes de transporte de motor y secuelas": "Motor transport accidents and sequelae",
    "accidentes por disparo de arma de fuego": "Firearm discharge accidents",
    "agresiones (homicidios) y secuelas": "Assault (homicide) and sequelae",
    "ahogamiento y sumersion accidentales": "Accidental drowning and submersion",
    "anemias: nutricionales, hemoliticas, aplasticas y otras": "Anemias: nutritional, hemolytic, aplastic and others",
    "aneurisma aortico": "Aortic aneurysm",
    "aterosclerosis": "Atherosclerosis",
    "caidas": "Falls",
    "ciertas enfermedades inmunoprevenibles": "Certain vaccine-preventable diseases",
    "ciertas enfermedades transmitidas por vectores y rabia": "Certain vector-borne diseases and rabies",
    "contratiempos de la atencion medico quirurgica y secuelas": "Misadventures of surgical and medical care and sequelae",
    "defectos de coagulacion, purpura y otras afecciones hemorragicas y de la sangre y los trastornos que afectan la inmunidad": "Coagulation defects, purpura and other hemorrhagic and blood conditions and immunity disorders",
    "deficiencias nutricionales": "Nutritional deficiencies",
    "diabetes mellitus": "Diabetes mellitus",
    "embarazo, parto y puerperio": "Pregnancy, childbirth and puerperium",
    "enfermedad cardiopulmonar y enfermedades de la circulacion pulmonar": "Cardiopulmonary disease and pulmonary circulation diseases",
    "enfermedad por el vih (sida)": "HIV disease (AIDS)",
    "enfermedades cerebrovasculares": "Cerebrovascular diseases",
    "enfermedades cronicas de las vias respiratorias inferiores": "Chronic lower respiratory diseases",
    "enfermedades de la piel y del tejido subcutaneo": "Diseases of the skin and subcutaneous tissue",
    "enfermedades de los vasos sanguineos y otras enfermedades del sistema circulatorio": "Diseases of blood vessels and other circulatory system diseases",
    "enfermedades del apendice, hernia y obstruccion intestinal": "Diseases of the appendix, hernia and intestinal obstruction",
    "enfermedades del esofago y otras enfermedades del estomago y del duodeno": "Diseases of the esophagus and other diseases of the stomach and duodenum",
    "enfermedades del higado": "Liver diseases",
    "enfermedades del ojo y sus anexos, del oido y de la apofisis mastoides": "Diseases of the eye and adnexa, ear and mastoid process",
    "enfermedades del peritoneo y todas las demas enfermedades del sistema digestivo": "Diseases of the peritoneum and all other digestive system diseases",
    "enfermedades del pulmon debidas a agentes externos": "Lung diseases due to external agents",
    "enfermedades del sistema osteomuscular y del tejido conjuntivo": "Diseases of the musculoskeletal system and connective tissue",
    "enfermedades glomerulares y tubulointersticiales": "Glomerular and tubulointerstitial diseases",
    "enfermedades hipertensivas": "Hypertensive diseases",
    "enfermedades infecciosas intestinales": "Intestinal infectious diseases",
    "enfermedades isquemicas del corazon": "Ischemic heart diseases",
    "enteritis, colitis no infecciosa y otras enfermedades de los intestinos": "Enteritis, non-infectious colitis and other intestinal diseases",
    "enterocolitis necrotizante del feto y del recien nacido": "Necrotizing enterocolitis of fetus and newborn",
    "envenenamiento accidental por, y exposicion a sustancias nocivas": "Accidental poisoning by and exposure to noxious substances",
    "epilepsia y otros trastornos episodicos y paroxisticos": "Epilepsy and other episodic and paroxysmal disorders",
    "eventos de intencion no determinada y secuelas": "Events of undetermined intent and sequelae",
    "exposicion a la corriente electrica, radiacion y temperatura y presion del aire ambientales extremas": "Exposure to electric current, radiation and extreme ambient air temperature and pressure",
    "exposicion al humo, fuego y llamas": "Exposure to smoke, fire and flames",
    "feto y recien nacido afectados por ciertas afecciones maternas": "Fetus and newborn affected by certain maternal conditions",
    "feto y recien nacido afectados por complicaciones obstetricas y traumatismo del nacimiento": "Fetus and newborn affected by obstetric complications and birth trauma",
    "fiebre reumatica aguda y enfermedades cardiacas reumaticas cronicas": "Acute rheumatic fever and chronic rheumatic heart diseases",
    "hemorragia gastrointestinal": "Gastrointestinal hemorrhage",
    "hepatitis viral y secuelas": "Viral hepatitis and sequelae",
    "hiperplasia de la prostata": "Hyperplasia of the prostate",
    "infecciones especificas del periodo perinatal": "Infections specific to the perinatal period",
    "insuficiencia cardiaca": "Heart failure",
    "insuficiencia renal": "Renal failure",
    "intervencion legal y operaciones de guerra y secuelas": "Legal intervention and operations of war and sequelae",
    "las demas malformaciones congenitas, deformidades y anomalias congenitas": "Other congenital malformations, deformities and congenital anomalies",
    "lesiones autoinfligidas intencionalmente (suicidios) y secuelas": "Intentional self-harm (suicide) and sequelae",
    "leucemia": "Leukemia",
    "los demas accidentes de transporte y los no especificados y secuelas": "Other and unspecified transport accidents and sequelae",
    "malformaciones congenitas del sistema circulatorio": "Congenital malformations of the circulatory system",
    "melanoma y otros tumores malignos de la piel": "Melanoma and other malignant skin tumors",
    "meningitis y otras enfermedades inflamatorias del sistema nervioso central": "Meningitis and other inflammatory diseases of the central nervous system",
    "neumonia": "Pneumonia",
    "otros accidentes de transporte terrestre": "Other land transport accidents",
    "otros accidentes que obstruyen la respiracion": "Other accidents obstructing breathing",
    "otros accidentes y secuelas": "Other accidents and sequelae",
    "retardo del crecimiento fetal, desnutricion fetal, gestacion corta y bajo peso al nacer": "Slow fetal growth, fetal malnutrition, short gestation and low birth weight",
    "septicemia, excepto neonatal": "Septicemia, except neonatal",
    "signos, sintomas y afecciones mal definidas": "Signs, symptoms and ill-defined conditions",
    "sifilis y otras enfermedades venereas": "Syphilis and other venereal diseases",
    "todas las demas afecciones originadas en el periodo perinatal": "All other conditions originating in the perinatal period",
    "todas las demas enfermedades bacterianas": "All other bacterial diseases",
    "todas las demas enfermedades del sistema nervioso": "All other nervous system diseases",
    "todas las demas enfermedades del sistema respiratorio": "All other respiratory system diseases",
    "todas las demas enfermedades del sistema urinario": "All other urinary system diseases",
    "todas las demas enfermedades endocrinas y nutricionales": "All other endocrine and nutritional diseases",
    "todas las demas enfermedades infecciosas y parasitarias": "All other infectious and parasitic diseases",
    "todas las demas formas de enfermedad del corazon": "All other forms of heart disease",
    "todos los demas tumores malignos de los organos digestivos y del peritoneo": "All other malignant tumors of the digestive organs and peritoneum",
    "todos los demas tumores malignos de los organos respiratorios e intratoracicos, excepto traquea, bronquios y pulmon": "All other malignant tumors of the respiratory and intrathoracic organs, except trachea, bronchi and lung",
    "todos los demas tumores malignos de los organos urinarios": "All other malignant tumors of the urinary organs",
    "todos los demas tumores malignos de otras localizaciones": "All other malignant tumors of other sites",
    "todos los demas tumores malignos del tejido linfatico, de los organos hematopoyeticos y de tejidos afines": "All other malignant tumors of lymphatic tissue, hematopoietic organs and related tissues",
    "trastornos de la vesicula biliar, de las vias biliares y del pancreas": "Disorders of the gallbladder, biliary tract and pancreas",
    "trastornos de los organos genitales": "Disorders of the genital organs",
    "trastornos hemorragicos y hematologicos del feto y del recien nacido": "Hemorrhagic and hematological disorders of the fetus and newborn",
    "trastornos mentales y del comportamiento": "Mental and behavioral disorders",
    "trastornos respiratorios especificos del periodo perinatal": "Respiratory disorders specific to the perinatal period",
    "tuberculosis y secuelas": "Tuberculosis and sequelae",
    "tumor maligno de la laringe": "Malignant tumor of the larynx",
    "tumor maligno de la mama de la mujer": "Malignant tumor of the female breast",
    "tumor maligno de la prostata": "Malignant tumor of the prostate",
    "tumor maligno de la traquea, los bronquios y el pulmon": "Malignant tumor of the trachea, bronchi and lung",
    "tumor maligno de la vejiga urinaria": "Malignant tumor of the urinary bladder",
    "tumor maligno de la vesicula biliar y de las vias biliares": "Malignant tumor of the gallbladder and biliary tract",
    "tumor maligno de los huesos y de los cartilagos articulares": "Malignant tumor of bones and articular cartilage",
    "tumor maligno de otras partes del utero": "Malignant tumor of other parts of the uterus",
    "tumor maligno de sitios no especificados": "Malignant tumor of unspecified sites",
    "tumor maligno del colon, de la union rectosigmoidea, recto y ano": "Malignant tumor of the colon, rectosigmoid junction, rectum and anus",
    "tumor maligno del cuello del utero": "Malignant tumor of the cervix",
    "tumor maligno del encefalo, del ojo y de otras partes del sistema nervioso central": "Malignant tumor of the brain, eye and other parts of the central nervous system",
    "tumor maligno del estomago": "Malignant tumor of the stomach",
    "tumor maligno del esofago": "Malignant tumor of the esophagus",
    "tumor maligno del higado": "Malignant tumor of the liver",
    "tumor maligno del ovario": "Malignant tumor of the ovary",
    "tumor maligno del pancreas": "Malignant tumor of the pancreas",
    "tumor maligno del tiroides y de otras glandulas endocrinas": "Malignant tumor of the thyroid and other endocrine glands",
    "tumores malignos de sitios mal definidos y secundarios": "Malignant tumors of ill-defined and secondary sites",
    "tumores malignos del labio, de la cavidad bucal y de la faringe": "Malignant tumors of the lip, oral cavity and pharynx",
    "tumores: in situ, benignos y de comportamiento incierto o desconocido y los no especificados": "Tumors: in situ, benign and of uncertain or unknown behavior and unspecified",
    "ulcera": "Ulcer",
}

# Coarser age buckets used by the department x municipality residence file (data/dane/deaths/departamento_municipio_residencia.csv).
AGE_MUNI_EN = {
    "Menor 1 año":      "Under 1 year",
    "De 1-4 años":      "1–4",
    "De 5-14 años":     "5–14",
    "De 15-44 años":    "15–44",
    "De 45-64 años":    "45–64",
    "De 65-84 años":    "65–84",
    "De 85-99 años":    "85–99",
    "De 100 y más":     "100+",
    "Edad desconocida": "Unknown",
}

# Coarser "grandes causas" classification used by the department x municipality residence file
# (different codes/wording than CAUSE_EN's ~112-code classification). Keyed on norm(stripped Spanish cause);
# accent/typo variants collapse to one entry.
CAUSE_MUNI_EN = {
    "signos, sintomas y afecciones mal definidas": "Signs, symptoms and ill-defined conditions",
    "enfermedades infecciosas intestinales": "Intestinal infectious diseases",
    "tuberculosis": "Tuberculosis",
    "ciertas enfermedades transmisibles por vectores y rabia": "Certain vector-borne diseases and rabies",
    "ciertas enfermedades inmunoprevenibles": "Certain vaccine-preventable diseases",
    "meningitis": "Meningitis",
    "septicemia, excepto neonatal": "Septicemia, except neonatal",
    "enfermedad por el vih (sida)": "HIV disease (AIDS)",
    "infecciones respiratorias agudas": "Acute respiratory infections",
    "resto de ciertas enfermedades infecciosas y parasitarias": "Remaining certain infectious and parasitic diseases",
    "tumor maligno del estomago": "Malignant tumor of the stomach",
    "tumor maligno del colon y de la union rectosigmoidea": "Malignant tumor of the colon and rectosigmoid junction",
    "tumo maligno de los organos digestivos y del peritoneo excepto estomago y colon": "Malignant tumor of the digestive organs and peritoneum, except stomach and colon",
    "tumor maligno de los organos digestivos y del peritoneo excepto estomago y colon": "Malignant tumor of the digestive organs and peritoneum, except stomach and colon",
    "tumor maligno de la traquea, los bronquios y el pulmon": "Malignant tumor of the trachea, bronchi and lung",
    "tumor maligno de los organos respiratorios e intratoracicos, excepto traquea, bronquios y pulmon": "Malignant tumor of the respiratory and intrathoracic organs, except trachea, bronchi and lung",
    "tumor maligno de la mama de la mujer": "Malignant tumor of the female breast",
    "tumor maligno del cuello del utero": "Malignant tumor of the cervix",
    "tumor maligno del cuerpo del utero": "Malignant tumor of the body of the uterus",
    "tumor maligno del utero, parte no especificada": "Malignant tumor of the uterus, part unspecified",
    "tumor maligno de la prostata": "Malignant tumor of the prostate",
    "tumor maligno de otros organos genitourinarios": "Malignant tumor of other genitourinary organs",
    "leucemia": "Leukemia",
    "tumo maligno del tejido linfatico, de otros organos hematopoyeticos y de tejidos afines": "Malignant tumor of lymphatic tissue, other hematopoietic organs and related tissues",
    "tumor maligno del tejido linfatico, de otros organos hematopoyeticos y de tejidos afines": "Malignant tumor of lymphatic tissue, other hematopoietic organs and related tissues",
    "tumores malignos de otras localizaciones y de las no especificadas": "Malignant tumors of other and unspecified sites",
    "tumores in situ, benignos y los de comportamiento incierto o desconocido": "Tumors in situ, benign and of uncertain or unknown behavior",
    "tumores in situ, beningnos y los de comportamiento incierto o desconocido": "Tumors in situ, benign and of uncertain or unknown behavior",
    "fiebre reumatica aguda y enfermedades reumaticas cronicas": "Acute rheumatic fever and chronic rheumatic diseases",
    "enfermedades hipertensivas": "Hypertensive diseases",
    "enfermedades isquemicas del corazon": "Ischemic heart diseases",
    "enfermedad cardiopulmonar, enfermedades de la circulacion pulmonar y otras formas de enfermedad del corazon": "Cardiopulmonary disease, pulmonary circulation diseases and other forms of heart disease",
    "paro cardiaco": "Cardiac arrest",
    "insuficiencia cardiaca": "Heart failure",
    "enfermedades cerebrovasculares": "Cerebrovascular diseases",
    "aterosclerosis": "Atherosclerosis",
    "las demas enfermedades del sistema circulatorio": "All other diseases of the circulatory system",
    "feto y recien nacido afectados por ciertas afecciones maternas": "Fetus and newborn affected by certain maternal conditions",
    "feto y recien nacido afectados por complicaciones obstetricas y traumatismo del nacimiento": "Fetus and newborn affected by obstetric complications and birth trauma",
    "retardo del crecimiento fetal, desnutricion fetal, gestacion corta y bajo peso al nacer": "Slow fetal growth, fetal malnutrition, short gestation and low birth weight",
    "trastornos respiratorios especificos del periodo perinatal": "Respiratory disorders specific to the perinatal period",
    "sepsis bacteriana del recien nacido": "Bacterial sepsis of the newborn",
    "resto de ciertas afecciones originadas en el periodo perinatal": "Remaining certain conditions originating in the perinatal period",
    "accidentes de transporte terrestre": "Land transport accidents",
    "los demas accidentes de transporte y los no especificados": "Other and unspecified transport accidents",
    "caidas": "Falls",
    "accidentes por disparo de arma de fuego": "Firearm discharge accidents",
    "ahogamiento y sumersion accidentales": "Accidental drowning and submersion",
    "accidentes que obstruyen la respiracion": "Accidents obstructing breathing",
    "exposicion a la corriente electrica": "Exposure to electric current",
    "exposicion al humo, fuego y llamas": "Exposure to smoke, fire and flames",
    "envenenamiento accidental por exposicion a sustancias nocivas": "Accidental poisoning by exposure to noxious substances",
    "otros accidentes, inclusive secuelas": "Other accidents, including sequelae",
    "lesiones autoinfligidas intencionalmente (suicidios)": "Intentional self-harm (suicide)",
    "agresiones (homicidios)": "Assault (homicide)",
    "eventos de intencion no determinada": "Events of undetermined intent",
    "las demas causas externas": "All other external causes",
    "diabetes mellitus": "Diabetes mellitus",
    "deficiencias nutricionales y anemias nutricionales": "Nutritional deficiencies and nutritional anemias",
    "trastornos mentales y del comportamiento": "Mental and behavioral disorders",
    "enfermedades del sistema nervioso, excepto meningitis": "Diseases of the nervous system, except meningitis",
    "enfermedades cronicas de las vias respiratorias inferiores": "Chronic lower respiratory diseases",
    "resto de enfermedades del sistema respiratorio": "Remaining diseases of the respiratory system",
    "apendicitis, hernia de la cavidad abdominal y obstruccion intestinal": "Appendicitis, abdominal cavity hernia and intestinal obstruction",
    "cirrosis y ciertas otras enfermedades croncas del higado": "Cirrhosis and certain other chronic liver diseases",
    "cirrosis y ciertas otras enfermedades cronicas del higado": "Cirrhosis and certain other chronic liver diseases",
    "resto de enfermedades del sistema digestivo": "Remaining diseases of the digestive system",
    "enfermedades del sistema urinario": "Diseases of the urinary system",
    "hiperplasia de la prostata": "Hyperplasia of the prostate",
    "embarazo, parto y puerperio": "Pregnancy, childbirth and puerperium",
    "malformaciones congenitas, deformidades y anomalias cromosomicas": "Congenital malformations, deformities and chromosomal abnormalities",
    "resto de las enfermedades": "All other diseases",
}

# Gap-filler for the muni_residence file's abroad-country spellings that don't norm-match
# migration.py's COUNTRY_EN (typos, DANE's 40-char field truncation, alternate phrasings).
# Keyed on norm(country text); the other ~82 countries already match COUNTRY_EN directly.
COUNTRY_MUNI_EN = {
    "antillas neerlandesas": "Netherlands Antilles",
    "bolivia": "Bolivia",
    "estado de la ciudad del vaticano (san": "Vatican City",
    "estado de la ciudad del vaticano (santa": "Vatican City",
    "holanda (paises bajos)": "Netherlands",
    "paises bajos (reino de los)": "Netherlands",
    "reino unido de gran bretana e irlanda": "United Kingdom",
    "republica popular del congo": "Republic of the Congo",
    "suriname": "Suriname",
    "territorios australes franceses": "French Southern Territories",
    "trinidad y tabago": "Trinidad and Tobago",
    "turkiye": "Turkey",
    "union de las comoras": "Comoros",
    "venezuela": "Venezuela",
}

MUNI_CAPTION = (
    "Uses a coarser cause/age classification than the other Deaths views, and shows the deceased's "
    "place of residence — not where the death occurred."
)
